# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller_name',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_no',
            field=models.IntegerField(blank=True),
        ),
    ]
