# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0003_auto_20160926_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='seller_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.Customer'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
