# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0004_auto_20160929_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('is_seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.User'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
